#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H
#define BTM_DEF_LOCAL_NAME "HTC Desire S"
#define BTA_DISABLE_DELAY 1000 /* in milliseconds */
#define I2SPCM_SLAVE_BRCM TRUE
#define BLE_INCLUDED FALSE
#define BTA_GATT_INCLUDED FALSE
#define SMP_INCLUDED FALSE
#define REMOVE_EAGER_THREADS FALSE
#endif
